FROM jenkins/jenkins:lts
MAINTAINER Sharad Durgawad <durgawad@gmail.com>
 
USER root

# Install latest Docker CE binaries and add user `jenkins` to docker group
RUN apt-get update && \
    apt-get -y install apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
      $(lsb_release -cs) \
      stable" && \
   apt-get update && \
   apt-get -y install docker-ce git maven default-jdk
   
RUN usermod -aG docker jenkins

RUN newgrp docker

# Switch to the regular jenkins user
USER jenkins